# Generated by Django 4.2.3 on 2023-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_colorvariant_sizevariant_product_color_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizevariant",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
